openapi: 3.0.3
info:
  title: Swagger Manutenzione - OpenAPI 3.0
  version: 1.0.11
tags:

  - name: Poi
    description: Gestione dei Poi
  - name: Percorso
    description: Gestione dei percorsi
  - name: Gps
    description: Gestione dei Gps
  - name: Notifiche
    description: Gestione delle notifiche satellitari

paths:
  /Poi:
    post:
      tags:
        - Poi
      summary: Inserimento nuovo Poi
      operationId: createPoi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoiDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoiDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Poi not found
    get:
      tags:
        - Poi
      summary: Leggi tutti i Poi
      operationId: getAllPoi
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PoiDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Poi not found
  /Percorso:
    post:
      tags:
        - Percorso
      summary: Creazione Percorso
      description: Creazione Percorso
      operationId: createPercorso
      parameters:
        - name: id_veicolo
          in: query
          required: true
          schema:
            type: integer
        - name: percorsoBreve
          in: query
          required: true
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PoiDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PercorsoDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
  /Percorso/{id}:
    delete:
      summary: Elimina un percorso
      description: Elimina un percorso dato il suo id
      tags:
        - Percorso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Percorso eliminato con successo
        '401':
          description: unauthorized
        '404':
          description: Percorso non trovato
  /Percorso/{id}/archivia:
    patch:
      summary: Archivia un percorso
      description: Archivia un percorso dato il suo id
      tags:
        - Percorso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Archivia eliminato con successo
        '401':
          description: unauthorized
        '404':
          description: Percorso non trovato
  /Percorso/poi/consegna:
    put:
      summary: Indica se è stata effettuata la consegna ad un Poi
      description: Indica se è stata effettuata la consegna ad un Poi
      operationId: aggiornaPoiConsegna
      tags:
        - Percorso
      parameters:
        - name: idPercorso
          in: query
          required: true
          schema:
            type: integer
        - name: idPoi
          in: query
          required: true
          schema:
            type: integer
        - name: consegnato
          in: query
          required: true
          schema:
            type: boolean
        - name: note
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Consegna segnata con successo
        '401':
          description: unauthorized
        '404':
          description: Percorso/Poi non trovato
  /Percorso/{id}/termina:
    put:
      summary: Permette di effettuare la chiusura di un percorso dopo aver effettuato tutte le consegne.
      description: Permette di effettuare la chiusura di un percorso
      operationId: terminaPercorso
      tags:
        - Percorso
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Consegna segnata con successo
        '401':
          description: unauthorized
        '404':
          description: Percorso/Poi non trovato
  /Percorso/ricerca:
    post:
      tags:
        - Percorso
      summary: Leggi percorsi
      operationId: getPercorsiByFilter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PercorsoSearchDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenerazionePercorsoDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Compagnia not found
  /Percorso/salvaPercorso:
    post:
      tags:
        - Percorso
      summary: Salvataggio Percorso
      description: Salvataggio Percorso
      operationId: savePercorso
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerazionePercorsoDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerazionePercorsoDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
  /Gps/localizza:
    get:
      tags:
        - Gps
      summary: Localizza Veicolo inviando il numero identificativo
      operationId: getPosizioneGpsVeicolo
      parameters:
        - name: numero
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoiDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Poi not found
  /Gps/percorso:
    get:
      tags:
        - Gps
      summary: Localizza Veicolo inviando il numero identificativo
      operationId: getPercorsoByDate
      parameters:
        - name: idDispositivo
          in: query
          required: true
          schema:
            type: string
        - name: dateStart
          in: query
          required: true
          schema:
            type: string
            format: date-time
            description: "Timestamp in ISO 8601 format"
        - name: dateEnd
          in: query
          required: true
          schema:
            type: string
            format: date-time
            description: "Timestamp in ISO 8601 format"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PercorsoDTO'
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Percorso not found
  /Notifiche/Leggi/Alert:
    put:
      tags:
        - Notifiche
      summary: Elimina Alert
      description: Elimina Alert
      operationId: deleteAlert
      parameters:
        - name: idDispositivo
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '401':
          description: unauthorized
        '400':
          description: Invalid ID supplied
        '404':
          description: Notifica not found
components:
  schemas:

    PercorsoSearchDTO:
      type: object
      properties:
        automezzo:
          type: integer
        autista:
          type: integer
        data :
          type: string
          format: date
        terminati:
          type: boolean
    GenerazionePercorsoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        percorso:
          $ref: '#/components/schemas/PercorsoDTO'
        automezzo:
          type: integer
          format: int32
        autista:
          type: integer
          format: int32


    PoiDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nome:
          type: string
        descrizione:
          type: string
        indirizzo:
          type: string
        latitudine:
          type: number
          format: double
        longitudine:
          type: number
          format: double
        ordine:
          type: integer
          format: int32

    NotificheDTO:
      type: object
      properties:
        numero_automezzo:
          type: integer
          format: int64
        targa_automezzo:
          type: string
        alert:
          type: array
          items:
            $ref: '#/components/schemas/SatellitareNotificaDTO'

    SatellitareNotificaDTO:
      type: object
      properties:
        id:
          type: integer
        iddevice:
          type: integer
        name:
          type: string
        icon:
          type: string
        bezeichnung:
          type: string
        meldung:
          type: string
        meldungtyp:
          type: integer
        dateunix:
          type: integer
        lat:
          type: number
          format: double
        lng:
          type: number
          format: double
        isread:
          type: integer
        imei:
          type: string
        speed:
          type: number
          format: double
        speederlaubt:
          type: number
          format: double
        radiusin:
          type: integer
        radiusout:
          type: integer
        zuendon:
          type: integer
        zuendoff:
          type: integer
        email:
          type: string
        push:
          type: integer

    PercorsoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        distance:
          type: number
          format: double
        terminato:
          type: boolean
        duration:
          type: number
          format: double
        shape:
          type: array
          items:
            type: string
        dataCreazione:
          type: string
          format: date
        poiPartenza:
          $ref: '#/components/schemas/PoiDTO'
        pois:
          type: array
          items:
            $ref: '#/components/schemas/PoiDTO'
        sigla:
          type: string